<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quotation;
use App\Models\QuotationItem;
use App\Models\Customer;
use App\Models\Product;
use Illuminate\Support\Str;

class QuotationSeeder extends Seeder
{
    public function run()
    {
        $customers = Customer::all();
        $products = Product::all();

        if ($customers->isEmpty() || $products->isEmpty()) {
            $this->command->warn('Customers or Products not found. Seed them first.');
            return;
        }

        foreach (range(1, 5) as $i) {
            $customer = $customers->random();

            $quotation = Quotation::create([
                'reference' => 'QUO-' . strtoupper(Str::random(6)),
                'customer_id' => $customer->id,
                'date' => now()->subDays(rand(1, 30)),
                'tax' => 0,
                'discount' => 0,
                'shipping' => rand(10, 50),
                'total_amount' => 0, // will update after items
                'status' => 'Pending',
                'note' => 'Generated by QuotationSeeder',
            ]);

            $total = 0;

            foreach (range(1, rand(1, 4)) as $j) {
                $product = $products->random();
                $quantity = rand(1, 5);
                $price = $product->price ?? rand(50, 200);
                $discount = rand(0, 10);
                $tax = rand(0, 15);
                $subtotal = ($price * $quantity) - $discount + $tax;

                QuotationItem::create([
                    'quotation_id' => $quotation->id,
                    'product_name' => $product->product_name,
                    'quantity' => $quantity,
                    'net_unit_price' => $price,
                    'discount' => $discount,
                    'tax' => $tax,
                    'subtotal' => $subtotal,
                ]);

                $total += $subtotal;
            }

            $quotation->update(['total_amount' => $total]);
        }

        $this->command->info('Sample quotations seeded successfully.');
    }
}
